Namespace Main
    Public Class ApiEndpoints
        Public Const SELECT_INIT As String = "/initializer/selectInitInfo"
        Public Const CODE_DATA As String = "/code/selectCodes"
        Public Const ITEM_CLASSIFICATION_SELECTOR As String = "/itemClass/selectItemsClass"
        Public Const CUSTOMER_LIST As String = "/customers/selectCustomer"
        Public Const SAVE_BRANCH_CUSTOMER As String = "/branches/saveBrancheCustomers"
        Public Const BRANCH_LIST As String = "/branches/selectBranches"
        Public Const BRANCH_INFO As String = "/branch/info"
        Public Const BRANCH_USER_SAVE As String = "/branches/saveBrancheUsers"
        Public Const BRANCH_INSURANCE_SAVE As String = "/branches/saveBrancheInsurances"
        Public Const ITEM_COMPOSITION_SAVE As String = "/items/saveItemComposition"
        Public Const ITEM_SAVE As String = "/items/saveItems"
        Public Const ITEM_SELECT As String = "/items/selectItems"
        Public Const IMPORT_ITEM_SELECT As String = "/imports/selectImportItems"
        Public Const IMPORT_ITEM_UPDATE As String = "/imports/updateImportItems"
        Public Const SALES As String = "/trnsSales/saveSales"
        Public Const PURCHASE_SELECT As String = "/trnsPurchase/selectTrnsPurchaseSales"
        Public Const PURCHASE_SAVE As String = "/trnsPurchase/savePurchases"
        Public Const STOCK_MOVEMENT_SAVE As String = "/stock/saveStockItems"
        Public Const STOCK_MOVEMENT_SELECT As String = "/stock/selectStockItems"
        Public Const STOCK_MASTER_SAVE As String = "/stockMaster/saveStockMaster"
        Public Const NOTICE_SELECT As String = "/notices/selectNotices"
    End Class
End Namespace
